# Generated by Django 5.1.6 on 2025-03-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="trackers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trackers",
                to="tracker.tracker",
                verbose_name="Задача",
            ),
        ),
    ]
