# Generated by Django 5.1.6 on 2025-03-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_trackers"),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to="employee.employee",
                verbose_name="Исполнитель",
            ),
        ),
    ]
